// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/counter/{bannerID}": {
            "get": {
                "description": "Increments click counter for specified banner",
                "tags": [
                    "banners"
                ],
                "summary": "Register banner click",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Banner ID",
                        "name": "bannerID",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Click registered successfully"
                    },
                    "400": {
                        "description": "Invalid banner ID"
                    },
                    "404": {
                        "description": "Banner not found"
                    },
                    "500": {
                        "description": "Internal server error"
                    }
                }
            }
        },
        "/stats/{bannerID}": {
            "post": {
                "description": "Returns click statistics for specified banner within time range",
                "tags": [
                    "banners"
                ],
                "summary": "Get banner statistics",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Banner ID",
                        "name": "bannerID",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Time range",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.StatsRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Statistics data",
                        "schema": {
                            "$ref": "#/definitions/models.StatsResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid request"
                    },
                    "404": {
                        "description": "Banner not found"
                    },
                    "500": {
                        "description": "Internal server error"
                    }
                }
            }
        }
    },
    "definitions": {
        "models.StatEntry": {
            "type": "object",
            "properties": {
                "ts": {
                    "type": "string",
                    "example": "2024-01-01T00:00:00"
                },
                "v": {
                    "type": "integer",
                    "example": 5
                }
            }
        },
        "models.StatsRequest": {
            "type": "object",
            "properties": {
                "from": {
                    "type": "string",
                    "example": "2024-01-01T00:00:00"
                },
                "to": {
                    "type": "string",
                    "example": "2024-01-02T00:00:00"
                }
            }
        },
        "models.StatsResponse": {
            "type": "object",
            "properties": {
                "stats": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.StatEntry"
                    }
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "Banner API",
	Description:      "Simple banner click tracking API",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
